### ISSUE TITLE
Исправить баг невозможности редактирования вопроса для checkbox и radio

### ISSUE THREAD

**Issue by Gollut** [VsevolodTrofimov/P-app#138]
При нажатии на вопрос внутри карточки с checkbox/radio, ничего не происходит

**Comment by Gollut** [comment]
При добавлении вопроса в карточку к checkbox/radio, текст вопроса остается стандартным. При попытке его редактирования, стандартный текст прибавляется к тексту пользователя

**Comment by VsevolodTrofimov** [comment]
Tested
...
None of these bugs found
